### ISSUE TITLE
Increase /Style the size of the text in Domain Label

### ISSUE THREAD

**Issue by smartmeter** [wa0x6e/cal-heatmap#172]
Hello, how can I 
*  increase the size of the text of the **DomainLabel users are find it hard to read**
*  make it high contrast and Bold

Also, is there a way to add month labels to the  calendar
Domain: year
SubDomain: Day

**Comment by wa0x6e** [comment]
To style the domainLabel, use the css:

```css
.cal-heatmap-container .graph-label {
  fill: #000;
  font-size: 16px;
  font-weight: bold;
}
```
